export const coreLines = [
  "Compiling project...",
  "Loading assets...",
  "Linking modules...",
  "Optimizing shaders...",
  "Building executable...",
  "Compilation successful.",
  "Running tests...",
  "All tests passed!",
  "Checking dependencies...",
  "Generating documentation...",
  "Packing resources...",
  "Deploying to staging environment...",
  "Migration script applied successfully",
  "Cache cleared",
  "Rendering frame 42",
  "Physics engine online",
  "Compiling sound assets...",
  "Applying post-processing effects...",
  "Initializing build pipeline...",
  "Parsing configuration files...",
  "Verifying asset integrity...",
  "Shader cache rebuilt",
  "Hot reload complete",
  "Thread pool initialized",
  "Garbage collection cycle finished",
  "Navmesh baked successfully",
  "AI behavior tree loaded",
  "Build target: release",
  "Symbols stripped",
  "Binary size optimized",
  "Frame pacing stabilized",
  "Audio middleware initialized",
  "Localization files loaded",
  "Telemetry disabled",
  "Profiling tools detached",
  "Build finished with warnings",
  "Entering idle state..."
];