export const devLifeLines = [
  "Warning: unused variable 'x'",
  "Error: missing semicolon",
  "Warning: Infinite loop detected",
  "Error: Undefined behavior imminent",
  "Debugging AI routines...",
  "Spawned 64 NPCs",
  "Warning: Player has too much fun",
  "Error: Cat not fed",
  "Tip: Remember to save frequently",
  "Warning: Coffee consumption critical",
  "Memory leak detected… just kidding",
  "Debugging in 3…2…1…",
  "Loading hidden Easter eggs...",
  "Warning: Nostalgia overload imminent",
  "TODO: refactor this later",
  "FIXME: temporary workaround applied",
  "Warning: magic number detected",
  "Error: works on my machine",
  "Refactoring legacy code...",
  "Recompiling because you blinked",
  "Debug build enabled",
  "Release build disabled (safety)",
  "Stack overflow avoided",
  "Unit tests skipped (living dangerously)",
  "Code review passed (somehow)",
  "Warning: coffee level critical",
  "Compiling patience module...",
  "Searching for missing semicolon...",
  "Naming variables is hard"
];