export const haloLines = [
  "Loading level: Installation 04",
  "Loading level: New Mombasa",
  "Loading level: Reach",
  "Loading level: Blood Gulch",
  "Dropping feet first into hell",
  "ODST squad deployed",
  "Slipspace rupture detected",
  "Shield strength nominal",
  "Warning: plasma overheating",
  "Grunt methane levels rising",
  "Thirsty Grunt detected",
  "Fortunately for us both, I like crazy",
  "Mjolnir armor systems online",
  "AI companion loaded: Cortana",
  "Remember: Spartans never die",
  "Incoming Covenant forces",
  "Warning: Needler shards detected",
  "Loading battle rifle...",
  "Spawning warthog physics bugs",
  "Mission objective updated",
  "Initializing Halo reference protocols...",
  "Loading 'Master Chief' skin...",
  "I would have been your daddy, but the dog beat me over the fence!"
];